rango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rangoapp.urls')),
    # path('rango/', include('rangoapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
  + static(settings.STATIC_URL, document_root=settings.STATIC_DIR)

rangoapp/urls.py
from django.urls import path
from . import views

app_name = 'rangoapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('category/<slug:category_name_slug>', views.category_view, name='category'),
    path('add_category/', views.add_category, name='add_category'),
    path('category/<slug:category_name_slug>/add_page/', views.add_page, name='add_page'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('goto/', views.goto, name='goto'),
    path('profile/<str:username>', views.profile, name='profile'),
    path('like/', views.like_category, name='like_category'),
    path('suggest/', views.suggest_category, name='suggest_category'),
    path('search_more/', views.search_more_pages, name='search_more'),
    path('profiles/', views.list_profiles, name='profiles'),
    path('auto_add_page/', views.auto_add_page, name='auto_add_page'),

]

rangoapp/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

# Create your models here.


class Category(models.Model):
    max_length = 128

    name = models.CharField(max_length=max_length, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Page(models.Model):
    max_length = 128

    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=max_length)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.name

rangoapp/forms.py
from django import forms
from rangoapp.models import Category, Page, UserProfile
from django.contrib.auth.models import User


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=Category.max_length,
                           label="Please enter the category name")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    # An inline class to provide additional information on the form.
    class Meta:
        # Provide an association between the ModelForm and a model
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=Page.max_length,
                            label="Please enter the title of the page")
    url = forms.URLField(max_length=200,
                         label="Please enter the URL of the page")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    def clean(self):
        cleaned_data = self.cleaned_data

        url = cleaned_data.get('url')
        # If url is not empty and doesn't start with 'http://',
        # then prepend 'http://'.
        if url and not url.startswith('http://'):
            url = 'http://' + url
        cleaned_data['url'] = url

        return cleaned_data

    class Meta:
        # Provide an association between the ModelForm and a model
        model = Page
        # Here, we are hiding the foreign key.
        # we can either exclude the category field from the form,
        exclude = ('category',)
        # or specify the fields to include (i.e. not include the category field)
        #fields = ('title', 'url', 'views')


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(), min_length=6)
    confirm_pwd = forms.CharField(widget=forms.PasswordInput(), min_length=6, label='Confirm password')

    def clean(self):
        cleaned_data = self.cleaned_data
        password = cleaned_data.get('password')
        confirm_pwd = cleaned_data.get('confirm_pwd')

        if password != confirm_pwd:
            self.add_error('confirm_pwd', 'Password confirmation and password are not the same')

        return cleaned_data

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    website = forms.URLField(required=False)
    picture = forms.ImageField(required=False)

    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

rangoapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from rangoapp.models import Category, Page, UserProfile
from django.contrib.auth.models import User
from rangoapp.forms import CategoryForm, PageForm, UserForm, UserProfileForm
from rangoapp.helpers import visitor_session_handler, get_category_list, get_google_results
from rango import settings


def index(request):
    """
    Index page view
    :param request: WSGIRequest object
    :return: HTTPResponse with content type 'text-html' - index page html
    """

    # set visitor cookie
    visitor_session_handler(request)

    return render(request, 'rangoapp/index.html', {
        'categories': Category.objects.order_by('-likes')[:5],
        'pages': Page.objects.order_by('-views')[:5],
        'visits': request.session['visits']
    })


def about(request):
    """
    About page view
    :param request: WSGIRequest object
    :return: HTTPResponse with content type 'text-html' - about page html
    """
    return render(request, 'rangoapp/about.html', {'my_name': 'Anna Lysak'})


def category_view(request, category_name_slug):
    """
    Category page view
    :param request: WSGIRequest object
    :return: HTTPResponse with content type 'text-html' - category page html
    """
    category = get_object_or_404(Category, slug=category_name_slug)
    category.views += 1
    category.save()

    pages = Page.objects.filter(category=category).order_by('-views')

    # Google search results for searching pages
    result_list = []
    query = ''
    if request.method == 'POST':
        query = request.POST['query'].strip()
        # Run Google search function to get the results list
        result_list = get_google_results(query)

    return render(request, 'rangoapp/category.html', {'category': category,
                                                      'pages': pages,
                                                      'result_list': result_list,
                                                      'query': query})


def suggest_category(request):
    """
    Suggest category view
    :param request: WSGIRequest object
    :return: HTTPResponse with content type 'text-html' - categories list according to search query
    """
    cat_list = []
    if request.method == 'GET':
        search_str = request.GET.get('search_str', '').strip()
        cat_list = get_category_list(search_str)
    return render(request, 'rangoapp/templatetags/cats.html', {'cats': cat_list})


@login_required
def search_more_pages(request):
    """
    Search pages view
    :param request: WSGIRequest object
    :return: HTTPResponse with content type 'text-html' - pages list according to search
    """
    result_list = []
    cat_id = 0
    if request.method == 'POST':
        query = request.POST['query'].strip()
        start = int(request.POST['start'])
        cat_id = int(request.POST['catid'])
        # Google returns up to 100 records for the query
        if query and start < 100:
            # Run Google search function to get the results list
            result_list = get_google_results(query, start=start)
    return render(request, 'rangoapp/parts/search_results.html', {'result_list': result_list,
                                                                  'category': {'id': cat_id}})


@login_required
def auto_add_page(request):
    """
    Add page to category and return newly updated category pages list
    :param request: WSGIRequest object
    :return: HTTPResponse with content type 'text-html' - pages list of certain category
    """
    pages = []
    page = None
    if request.method == 'POST':
        cat_id = request.POST['category_id']
        url = request.POST['url']
        title = request.POST['title']
        category = Category.objects.get(id=int(cat_id))
        if category:
            page = Page.objects.get_or_create(category=category, title=title, url=url)
            pages = Page.objects.filter(category=category).order_by('-views')
    return render(request, 'rangoapp/parts/page_list.html', {'pages': pages, 'page': page})


@login_required
def like_category(request):
    """
    Increase likes amount of category
    :param request: WSGIRequest object
    :return: HTTPResponse with content type 'text-html' - number of likes of category
    """
    likes = 0
    if request.method == 'POST':
        cat_id = request.POST['category_id']
        if cat_id:
            cat = Category.objects.get(id=int(cat_id))
            if cat:
                cat.likes += 1
                cat.save()
                likes = cat.likes
    return HttpResponse(likes)


@login_required
def add_category(request):
    """
    Add category view
    :param request: WSGIRequest object
    :return: HTTPResponse with content type 'text-html' - add category form or redirect to index view
    """
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return redirect(reverse('rangoapp:index'))
        else:
            print(form.errors)

    return render(request, 'rangoapp/add_category.html', {'form': form})


@login_required
def add_page(request, category_name_slug):
    """
    Add page view
    :param request: WSGIRequest object
    :param category_name_slug: category slug to add page
    :return: HTTPResponse with content type 'text-html' - add page to category form or redirect to category page
    """
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    form = PageForm()

    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()

            return redirect(reverse('rangoapp:category', args=(category_name_slug,)))
        else:
            print(form.errors)

    return render(request, 'rangoapp/add_page.html', {'form': form, 'category': category})


def goto(request):
    """
    Increases number of views of the page and redirect to page url
    :param request: WSGIRequest object
    :param category_name_slug: category slug to add page
    :return: redirect to category page
    """
    page_number = int(request.GET.get('page', 0))
    if page_number:
        page = Page.objects.get(id=page_number)
        if page:
            page.views += 1
            page.save()

            return redirect(page.url)

    return redirect(reverse('rangoapp:index'))


def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        user_profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and user_profile_form.is_valid():
            user = user_form.save()
            # hash password with set_password method
            user.set_password(user.password)
            user.save()

            profile = user_profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()

            registered = True
            try:
                # try to login new registered user
                user = authenticate(username=user.username,
                                    password=request.POST.get('password'))
                if user and user.is_active:
                    login(request, user)
            except Exception as e:
                print("Exception, ", str(e))
                pass

        else:
            print(user_form.errors, user_profile_form.errors)
    else:
        user_form = UserForm()
        user_profile_form = UserProfileForm()

    return render(request, 'rangoapp/register.html', {
        'user_form': user_form,
        'user_profile_form': user_profile_form,
        'registered': registered
    })


def user_login(request):
    error_msg = None

    redirect_next = request.GET.get('next', '/')

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(redirect_next)
            else:
                error_msg = 'Your Rango account is disabled.'
        else:
            error_msg = 'Invalid login details supplied.'

    return render(request, 'rangoapp/login.html', {'error_msg': error_msg, 'next': redirect_next})


@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse('rangoapp:index'))



@login_required
def profile(request, username):
    try:
        user = User.objects.get(username=username)
    except User.DoesNotExist:
        return redirect(reverse('rangoapp:index'))

    userprofile = UserProfile.objects.get_or_create(user=user)[0]
    form = UserProfileForm({'website': userprofile.website, 'picture': userprofile.picture})
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=userprofile)
        if form.is_valid():
            form.save(commit=True)
            return redirect(reverse('rangoapp:profile', args=(user.username,)))
        else:
            print(form.errors)

    return render(request, 'rangoapp/profile.html', {'userprofile': userprofile,
                                                     'selecteduser': user,
                                                     'form': form})



@login_required
def list_profiles(request):

templates/rangoapp/about.html
{% extends 'rangoapp/base.html' %}

{% block title_block %}
    About
{% endblock %}

{% block page_title %}
    <h1>About</h1>
{% endblock %}

{% block sidebar %}{% endblock %}
{% block right_side_width %}<div class="col-sm-12">{% endblock %}


{% block body_block %}
<div>
    This web site has been created by {{ my_name }} in frames of learning Django framework by following instructions from "Tango With Django 1.9" book. <br /><br/>
    <img src="{{ MEDIA_URL }}ballerina.jpg" alt="Just a picture" width="550" height="350"  />
</div>
{% endblock %}

templates/rangoapp/add_category.html
{% extends 'rangoapp/base.html' %}

{% block title_block %}
    Add a Category
{% endblock %}

{% block page_title %}
    <h1>Add a Category</h1>
{% endblock %}

{% block body_block %}
    <form id="category_form" method="post" action="{% url 'rangoapp:add_category' %}">
    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
        {{ hidden }}
    {% endfor %}
    {% for field in form.visible_fields %}
        <div class="form-group">
            {{ field.errors }}
            {{ field.label }}<br/>
            {{ field }}
        </div>
    {% endfor %}
        <button class="btn btn-primary" type="submit">Create Category</button>
    </form>
{% endblock %}

templates/rangoapp/add_page.html
{% extends 'rangoapp/base.html' %}

{% block title_block %}
    Add Page
{% endblock %}

{% block page_title %}
    <h1>Add Page to {{ category.name }}</h1>
{% endblock %}

{% block body_block %}
    <form id="page_form" method="post" action="{% url 'rangoapp:add_page' category.slug %}">
    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
        {{ hidden }}
    {% endfor %}
    {% for field in form.visible_fields %}
        <div class="form-group">
            {{ field.errors }}
            {{ field.label }}<br/>
            {{ field }}
        </div>
    {% endfor %}
        <button class="btn btn-primary" type="submit">Create Page</button>
    </form>
{% endblock %}

templates/rangoapp/base.html
<!DOCTYPE html>
{% load static %}
{% load rangoapp_template_tags %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Rango App">
    <meta name="author" content="Anna Lysak">
    <title>Rango -
            {% block title_block %}
                How to Tango With Django
            {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
</head>
<body>

    <!-- NAVIGATION MENU -->
    <nav class="navbar navbar-inverse">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'rangoapp:index' %}">Rango</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'rangoapp:index' %}"><span class="glyphicon glyphicon-home"></span> Home</a></li>
            <li><a href="{% url 'rangoapp:about' %}"><span class="glyphicon glyphicon-info-sign"></span> About</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'rangoapp:add_category' %}"><span class="glyphicon glyphicon-plus"></span> Add New Category</a></li>
            {% endif %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'rangoapp:register' %}"><span class="glyphicon glyphicon-edit"></span> Sign Up</a></li>
            {% if not user.is_authenticated %}
            <li><a href="{% url 'rangoapp:login' %}"><span class="glyphicon glyphicon-log-in"></span> Log In</a></li>
            {% else %}
            <li><a href="{% url 'rangoapp:profile' user.username %}"><span class="glyphicon glyphicon-user"></span> Profile</a></li>
            <li><a href="{% url 'rangoapp:logout' %}"><span class="glyphicon glyphicon-log-out"></span> Log Out</a></li>
            {% endif %}
          </ul>
        </div>
    </nav>

    <div class="container-fluid" >
        <!-- SIDEBAR: CATEGORIES SEARCH, CATEGORIES LIST -->
        {% block sidebar %}
        <div class="navbar sidenav col-sm-2" id="sidenav">
            <div class="side-cats">
                <div class="form-group">
                    <form>
                        <label for="suggestion">Type to find a category</label>
                        <input class="search-query form-control" type="text" name="suggestion" value="" id="suggestion" />
                    </form>
                </div>
                <div id="cats"></div>

                <hr/>

                {% get_category_list category %}

                {% if user.is_authenticated %}
                <div>
                    <br/>
                    <a href="{% url 'rangoapp:add_category' %}"><strong><u>Add New Category</u></strong></a>
                </div>
                {% endif %}
            </div>
        </div>
        {% endblock %}

        <!-- RIGHT SIDE -->
        {% block right_side_width %}<div class="col-sm-10">{% endblock %}
            <div class="jumbotron jumbotron-fluid text-center">
                {% block page_title %}{% endblock%}
            </div>

             <!-- PAGE CONTENT -->
             <div class="col-sm-12 text-left">
                {% block body_block %}{% endblock %}
            </div>
        </div>

    </div>

    <!-- LOAD JavaScript -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/rango.js' %}"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

</body>
</html>

templates/rangoapp/category.html
{% extends 'rangoapp/base.html' %}

{% block title_block %}
    {{ category.name}}
{% endblock %}

{% block page_title %}
    {% if category %}
        <h1>{{ category.name }}</h1>
    {% else %}
        <h1>Category</h1>
    {% endif%}
{% endblock %}

{% block body_block %}
    {% if category %}
        <div>
            <strong id="like_count">{{ category.likes }}</strong> people like this category
            {% if user.is_authenticated %}
                <button id="likes" data-catid="{{category.id}}" class="btn btn-primary btn-sm" type="button">
                    <span class="glyphicon glyphicon-thumbs-up"></span>&nbsp;Like
                </button>
            {% endif %}
            <br/>
        </div>

        <!-- PAGES -->
        <h3>Pages in this category</h3>
        <div id="pages">
            {% include 'rangoapp/parts/page_list.html' %}
        </div>

        {% if user.is_authenticated %}
            <div>
                <br/>
                <a href="{% url 'rangoapp:add_page' category.slug %}"><strong><u>Add Page</u></strong></a><br/>
            </div>

            <!-- GOOGLE SEARCH FUNCTIONALITY WITHIN CATEGORY -->
            <div>
                <br/>
                <h3>Search for pages</h3>

                <form class="form-inline" id="user_form" method="post" action="{% url 'rangoapp:category' category.slug %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <input class="form-control" type="text" size="50" name="query" value="{{ query }}" id="query" />
                        <input type="hidden" name="start" value="1" id="start" />
                        <input type="hidden" name="catid" value="{{ category.id }}" id="catid" />
                    </div>
                    <button class="btn btn-primary" type="submit" name="submit" value="Search" id="search-pages">Search</button>
                </form>
                <div>
                {% if result_list %}
                    <h3>Results</h3>
                    <!-- Display search results in an ordered list -->
                    <div class="list-group" id="search_results">
                        {% include 'rangoapp/parts/search_results.html' %}
                    </div>
                {% endif %}
                    <br/>
                    <div class="loader"></div>
                </div>
            </div>
            <!-- END OF GOOGLE SEARCH WITHIN CATEGORY -->
        {% endif %}

    {% else %}
        The specified category does not exist!
    {% endif %}

{% endblock %}

templates/rangoapp/index.html
{% extends 'rangoapp/base.html' %}

{% block title_block %}Index{% endblock %}

{% block page_title %}
<h1>Rango says ...</h1>
<div>
    <h3>hey there,
        {% if user.is_authenticated %}
            {{ user.username }}
        {% else %}
            partner
        {% endif%}
    !</h3>
</div>
{% endblock%}

{% block body_block %}
<!-- MOST LIKED CATEGORIES -->
<div class="col-sm-4 text-left">
    <h3>Most Liked Categories</h3>
    <div class="list-group-item" >
        {% for category in categories %}
            <div>
                <a class="list-group-item-text" href="{% url 'rangoapp:category' category.slug %}">{{ category.name }}</a>&nbsp;
                <div class="btn-info badge">{{ category.likes}}</div><br/>
            </div>
        {% empty %}
            <strong>There are no categories present.</strong>
        {% endfor %}
    </div>
</div>

<!-- MOST VIEWED PAGES -->
<div class="col-sm-4 text-left">
    <h3>Most Viewed Pages</h3>
    <div class="list-group-item" >
        {% for page in pages %}
            <div>
                <a class="list-group-item-text" href="{% url 'rangoapp:goto' %}?page={{ page.id }}">{{ page.title }}</a>&nbsp;
                <div class="btn-info badge">{{ page.views }}</div><br/>
            </div>
        {% empty %}
            <strong>There are no pages present.</strong>
        {% endfor %}
    </div>
</div>

<!-- VISITS -->
<div class="col-sm-12 text-left">
    <br/><br/>
    <p>Visits: {{ visits }}</p>
</div>
{% endblock %}

templates/rangoapp/login.html
{% extends 'rangoapp/base.html' %}
{% load static %}
{% block title_block %}
Login
{% endblock %}

{% block page_title %}
<h1>Login to Rango</h1>
{% endblock %}

{% block sidebar %}{% endblock %}
{% block right_side_width %}<div class="col-sm-12">{% endblock %}

{% block body_block %}

    <div class="col-sm-5"><br/></div>
    <div class="col-sm-4">
    {% if error_msg %}
        <div class="panel panel-danger">
            <div class="panel-heading"><strong>{{ error_msg }}</strong></div>
        </div>
    {% endif %}

    <form id="login_form" method="post" action="{% url 'rangoapp:login'%}?next={{ next }}">
    {% csrf_token %}
    Username: <br/><input type="text" name="username" value="" size="50" />
    <br /><br/>
    Password: <br/><input type="password" name="password" value="" size="50" />
    <br /><br/>
    <input type="submit" value="Log In" class="btn btn-primary" />

    </form>
    </div>


{% endblock %}

templates/rangoapp/profile.html
{% extends 'rangoapp/base.html' %}

{% load static %}

{% block title %}{{ selecteduser.username }} Profile{% endblock %}

{% block page_title %}
<h1>{{selecteduser.username}} Profile</h1>{% endblock %}

{% block sidebar %}{% endblock %}
{% block right_side_width %}<div class="col-sm-12">{% endblock %}

{% block body_block %}
<div class="col-sm-3">
<img src="{{ MEDIA_URL }}{{ userprofile.picture }}" width="100%" height="150" alt="{{selecteduser.username}}" />
</div>
<div class="col-sm-2">
    <br/><br/>
{% if selecteduser.username == user.username and user.is_authenticated %}
    <form id="user_form" method="post" action="{% url 'rangoapp:profile' user.username %}" enctype="multipart/form-data">
    {% csrf_token %}
    <!-- Display each form -->
    {% for field in user_form.visible_fields %}
        <div class="form-group">
            {{ field.errors }}
            {{ field.label }}<br/>
            {{ field }} {{ field.help_text }}
        </div>
    {% endfor %}

    {% for field in form.visible_fields %}
        <div class="form-group">
            {{ field.errors }}
            {{ field.label }}<br/>
            {{ field }} {{ field.help_text }}
        </div>
    {% endfor %}

    <!-- Provide a button to click to submit the form. -->
    <input type="submit" class="btn btn-primary" name="submit" value="Update" />
    </form>
{% else %}
    <p><strong>Website:</strong> <a href="{{userprofile.website}}">{{userprofile.website}}</a></p>
{% endif %}
    <br/>
    <br/>
    <a href="{% url 'rangoapp:profiles' %}"><strong> Profiles List</strong></a>

</div>
{% endblock %}

templates/rangoapp/register.html
{% extends 'rangoapp/base.html' %}
{% load static %}
{% block title_block %}
    Register
{% endblock %}

{% block page_title %}
<h1>Register for Rango</h1>
{% endblock %}

{% block sidebar %}{% endblock %}
{% block right_side_width %}<div class="col-sm-12">{% endblock %}

{% block body_block %}

<div class="col-sm-5"><br/></div>
<div class="col-sm-4">

{% if registered %}
    <h4><strong>Thank you for registering!</strong></h4><br/>
    <a href="{% url 'rangoapp:index' %}">Return to the homepage</a><br />
{% else %}
    <h3><strong>Register here:</strong></h3><br/>
    <form id="user_form" method="post" action="{% url 'rangoapp:register' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <!-- Display each form -->
    {% for field in user_form.visible_fields %}
        <div class="form-group">
            {{ field.errors }}
            {{ field.label }}<br/>
            {{ field }} {{ field.help_text }}
        </div>
    {% endfor %}

    {% for field in user_profile_form.visible_fields %}
        <div class="form-group">
            {{ field.errors }}
            {{ field.label }}<br/>
            {{ field }} {{ field.help_text }}
        </div>
    {% endfor %}

    <!-- Provide a button to click to submit the form. -->
    <input type="submit" class="btn btn-primary" name="submit" value="Register" />
    </form>
{% endif %}
</div>
{% endblock %}

templates/rangoapp/user_profiles.html
{% extends 'rangoapp/base.html' %}
{% load static %}
{% block title %}User Profiles{% endblock %}
{% block page_title %}<h1>User Profiles</h1>{% endblock %}
{% block sidebar %}{% endblock%}
{% block right_side_width %}<div class="col-sm-12">{% endblock %}

{% block body_block %}

{% for listuser in userprofile_list %}
<div class="col-sm-3 text-center">
    <br/>
    <div class="card">
      {% if listuser.picture %}
      <img src="{{ MEDIA_URL }}{{ listuser.picture }}"  alt="{{listuser.user.username}}">
      {% else %}
      <img src="{% static 'images/rango.jpg' %}"  alt="{{listuser.user.username}}">
      {% endif %}
      <div class="card-container">
        <h4><b><a href="{% url 'rangoapp:profile' listuser.user.username %}">{{ listuser.user.username }}</a></b></h4>

      </div>
    </div>
</div>
{% empty %}
    <p>There are no users for the site.</p>
{% endfor %}
</div>
{% endblock %}